// This file provides Kotlin bindings for zvault-core via UniFFI.
//
// In a full build pipeline, this file is AUTO-GENERATED by uniffi-bindgen from
// `bindings/uniffi/src/zvault.udl`.  It is committed to the repository so that
// the Android Gradle build does not require the Rust toolchain at compile time.
//
// To regenerate after changing the UDL:
//   uniffi-bindgen generate bindings/uniffi/src/zvault.udl \
//       --language kotlin \
//       --out-dir apps/android/app/src/main/java/com/zvault/uniffi/
//
// See also: bindings/uniffi/README.md

@file:Suppress("NAME_SHADOWING", "NOTHING_TO_INLINE", "KotlinRedundantDiagnosticSuppress")

package com.zvault.uniffi

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.ptr.PointerByReference

// ─── Error type ──────────────────────────────────────────────────────────────

/**
 * Exception type corresponding to the Rust `ZVaultError` enum.
 */
sealed class ZVaultException(message: String) : Exception(message) {
    class CryptoException(message: String) : ZVaultException(message)
    class IoException(message: String) : ZVaultException(message)
    class SerialisationException(message: String) : ZVaultException(message)
    class InvalidVaultFileException(message: String) : ZVaultException(message)
    class ItemNotFoundException(message: String) : ZVaultException(message)
    class InvalidInputException(message: String) : ZVaultException(message)
}

// ─── Data types ──────────────────────────────────────────────────────────────

/**
 * Opaque handle to an open vault session on the Rust side.
 *
 * The [id] field is used internally to look up the session in the Rust global
 * registry.  Callers should treat this as opaque.
 */
data class VaultHandle(
    val id: ULong,
)

// ─── Internal JNA interface ──────────────────────────────────────────────────

/**
 * JNA interface to the `libzvault_uniffi` shared library.
 *
 * These are the raw C-ABI functions exported by the UniFFI scaffolding.
 * They are not called directly by application code — use the top-level
 * wrapper functions below instead.
 */
private interface ZVaultLib : Library {
    companion object {
        internal val INSTANCE: ZVaultLib by lazy {
            Native.load("zvault_uniffi", ZVaultLib::class.java)
        }
    }

    // --- Vault lifecycle ---
    fun zvault_e7d4_create_vault(
        password: String,
        path: String,
        out_err: PointerByReference,
    ): Long

    fun zvault_e7d4_open_vault(
        password: String,
        path: String,
        out_err: PointerByReference,
    ): Long

    fun zvault_e7d4_save_vault(
        handle_id: Long,
        out_err: PointerByReference,
    )

    fun zvault_e7d4_close_vault(
        handle_id: Long,
        out_err: PointerByReference,
    )

    // --- Item CRUD ---
    fun zvault_e7d4_list_items(
        handle_id: Long,
        out_err: PointerByReference,
    ): String?

    fun zvault_e7d4_get_item(
        handle_id: Long,
        item_id: String,
        out_err: PointerByReference,
    ): String?

    fun zvault_e7d4_add_item(
        handle_id: Long,
        item_json: String,
        out_err: PointerByReference,
    )

    fun zvault_e7d4_delete_item(
        handle_id: Long,
        item_id: String,
        out_err: PointerByReference,
    )

    // Error string retrieval and free
    fun zvault_e7d4_error_msg_get(err: Pointer): String?
    fun zvault_e7d4_error_msg_free(err: Pointer)
}

// ─── Internal helpers ────────────────────────────────────────────────────────

/**
 * Checks the error pointer after a JNA call.  If the pointer is non-null,
 * reads the error message, frees the Rust-allocated string, and throws the
 * appropriate [ZVaultException] subclass.
 */
private fun checkError(errRef: PointerByReference) {
    val errPtr = errRef.value ?: return
    val msg = ZVaultLib.INSTANCE.zvault_e7d4_error_msg_get(errPtr) ?: "unknown error"
    ZVaultLib.INSTANCE.zvault_e7d4_error_msg_free(errPtr)
    // The Rust side encodes the error variant as a prefix.
    // For simplicity, map based on known prefix patterns.
    throw when {
        msg.startsWith("crypto error") -> ZVaultException.CryptoException(msg)
        msg.startsWith("io error") -> ZVaultException.IoException(msg)
        msg.startsWith("serialisation error") -> ZVaultException.SerialisationException(msg)
        msg.startsWith("invalid vault file") -> ZVaultException.InvalidVaultFileException(msg)
        msg.startsWith("item not found") -> ZVaultException.ItemNotFoundException(msg)
        msg.startsWith("invalid input") -> ZVaultException.InvalidInputException(msg)
        else -> ZVaultException.IoException(msg)
    }
}

// ─── Public API ──────────────────────────────────────────────────────────────
//
// These functions mirror the UDL namespace functions and are the intended
// public interface for Kotlin callers.

/**
 * Create a new vault at [path], encrypted with [password].
 *
 * @return A [VaultHandle] that must be passed to subsequent operations.
 * @throws ZVaultException on crypto or I/O failure.
 */
@Throws(ZVaultException::class)
fun createVault(password: String, path: String): VaultHandle {
    val errRef = PointerByReference()
    val id = ZVaultLib.INSTANCE.zvault_e7d4_create_vault(password, path, errRef)
    checkError(errRef)
    return VaultHandle(id.toULong())
}

/**
 * Open an existing vault at [path] with [password].
 *
 * @return A [VaultHandle] that must be passed to subsequent operations.
 * @throws ZVaultException on wrong password, corrupt file, or I/O failure.
 */
@Throws(ZVaultException::class)
fun openVault(password: String, path: String): VaultHandle {
    val errRef = PointerByReference()
    val id = ZVaultLib.INSTANCE.zvault_e7d4_open_vault(password, path, errRef)
    checkError(errRef)
    return VaultHandle(id.toULong())
}

/**
 * Save the current vault state to disk.
 *
 * Uses the stored KDF params so the in-memory key remains valid.
 *
 * @throws ZVaultException on I/O failure or invalid handle.
 */
@Throws(ZVaultException::class)
fun saveVault(handle: VaultHandle) {
    val errRef = PointerByReference()
    ZVaultLib.INSTANCE.zvault_e7d4_save_vault(handle.id.toLong(), errRef)
    checkError(errRef)
}

/**
 * Close the vault session.  The Rust side will zero the key material.
 *
 * After this call the [handle] is invalid — any subsequent use will throw.
 *
 * @throws ZVaultException if the handle is already closed or invalid.
 */
@Throws(ZVaultException::class)
fun closeVault(handle: VaultHandle) {
    val errRef = PointerByReference()
    ZVaultLib.INSTANCE.zvault_e7d4_close_vault(handle.id.toLong(), errRef)
    checkError(errRef)
}

/**
 * List all items in the vault as a JSON array string.
 *
 * @return JSON string representing `List<VaultItem>`.
 * @throws ZVaultException if the handle is invalid.
 */
@Throws(ZVaultException::class)
fun listItems(handle: VaultHandle): String {
    val errRef = PointerByReference()
    val json = ZVaultLib.INSTANCE.zvault_e7d4_list_items(handle.id.toLong(), errRef)
    checkError(errRef)
    return json ?: "[]"
}

/**
 * Get a single item by UUID string, returned as JSON.
 *
 * @return JSON string representing a single `VaultItem`.
 * @throws ZVaultException if the item is not found or handle is invalid.
 */
@Throws(ZVaultException::class)
fun getItem(handle: VaultHandle, itemId: String): String {
    val errRef = PointerByReference()
    val json = ZVaultLib.INSTANCE.zvault_e7d4_get_item(handle.id.toLong(), itemId, errRef)
    checkError(errRef)
    return json ?: "{}"
}

/**
 * Add a new item to the vault.
 *
 * @param handle Open vault handle.
 * @param itemJson JSON string representing the item to add.
 * @throws ZVaultException on serialisation failure or invalid handle.
 */
@Throws(ZVaultException::class)
fun addItem(handle: VaultHandle, itemJson: String) {
    val errRef = PointerByReference()
    ZVaultLib.INSTANCE.zvault_e7d4_add_item(handle.id.toLong(), itemJson, errRef)
    checkError(errRef)
}

/**
 * Delete an item by UUID string.
 *
 * @throws ZVaultException if the item is not found or handle is invalid.
 */
@Throws(ZVaultException::class)
fun deleteItem(handle: VaultHandle, itemId: String) {
    val errRef = PointerByReference()
    ZVaultLib.INSTANCE.zvault_e7d4_delete_item(handle.id.toLong(), itemId, errRef)
    checkError(errRef)
}
